tuxmake-offline-build: fail early without socat
This avoids failing late, only when socat is actually needed. If socat
is not available, tuxmake will detect that offline builds are not
supported, and fallback to doing an online build.

Fixes: https://gitlab.com/Linaro/tuxmake/-/issues/130

diff --git a/tuxmake/runtime/tuxmake-offline-build b/tuxmake/runtime/tuxmake-offline-build
--- a/tuxmake/runtime/tuxmake-offline-build
+++ b/tuxmake/runtime/tuxmake-offline-build
@@ -5,6 +5,11 @@ set -eu
 if [ -z "${TUXMAKE_OFFLINE_BUILD:-}" ]; then
     # initial call: here we still have network access
 
+    if ! command -v socat >/dev/null; then
+        echo "socat not found" >&2
+        exit 1
+    fi
+
     if [ -n "${TUXMAKE_OFFLINE_BUILD_ALLOW_LOCAL_PORT:-}" ]; then
         # determine socket location
         uid="$(id -u)"
